version: "2"

checks:
  method-count:
    enabled: false # use rubocop's
  method-lines:
    enabled: false # use rubocop's

plugins:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 20
        javascript:
          mass_threshold: 20
  brakeman:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-1-7-0"
  reek:
    enabled: false
  flog:
    enabled: false
  bundler-audit:
    enabled: true
