require: rubocop-rails

Rails:
  Enabled: true

  Rails/NotNullColumn:
    Enabled: false

AllCops:
  Exclude:
    - './db/schema.rb'
    - './bin/**/*'
    - './vendor/**/*'
    - './node_modules/**/*'
    - './tmp/**/*'
    - './config/**/*'
    - './lib/tasks/*.rake'
    - './Guardfile'
    - './Dangerfile'
  NewCops: enable
  TargetRubyVersion: 3.0.1

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 20
  Exclude:
    - './db/**/*'

Metrics/BlockLength:
  Exclude:
    - './Rakefile'
    - './lib/**/*.rake'
    - './spec/**/*'
    - './db/migrate/**'
    - './config/routes.rb'

Style/FormatStringToken:
  Exclude:
    - './config/routes.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - './spec/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - './db/migrate/**'
    - './spec/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
