default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_POSTGRESQL_POOL') { 5 } %>
  timeout: <%= ENV.fetch('RAILS_POSTGRESQL_TIMEOUT') { 5000 } %>

development:
  <<: *default
  database: agendamento_covid_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { 'postgres' } %>
  host: localhost
  port: 9999

test:
  <<: *default
  encoding: utf8
  timeout: 5000
  database: agendamento_covid_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { 'postgres' } %>
  host: localhost
  port: 9999

production:
  <<: *default
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
