default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # https://devcenter.heroku.com/articles/concurrency-and-database-connections
  pool: <%= ENV.fetch('RAILS_POSTGRESQL_POOL') { ENV.fetch('RAILS_MAX_THREADS') { 5 } } %>
  timeout: <%= ENV.fetch('RAILS_POSTGRESQL_TIMEOUT') { 5000 } %>

development:
  <<: *default
  database: agendamento_covid_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { '' } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRESQL_PORT') { '5432' } %>

test:
  <<: *default
  encoding: utf8
  timeout: 5000
  database: agendamento_covid_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { '' } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRESQL_PORT') { '5432' } %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # PgBouncer does not support prepared statements
  prepared_statements: false
