default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # https://devcenter.heroku.com/articles/concurrency-and-database-connections
  pool: <%= ENV.fetch('RAILS_POSTGRESQL_POOL') { ENV.fetch('RAILS_MAX_THREADS') { 5 } } %>
  timeout: <%= ENV.fetch('RAILS_POSTGRESQL_TIMEOUT') { 5000 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres:@localhost:5432/agendamento_covid_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/agendamento_covid_test") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
  # PgBouncer does not support prepared statements
  prepared_statements: false
